version: "3"
services:
    app:
        build: .
        command: >
          sh -c "npm run dev &&
                npx sequelize-cli db:create &&
                npx sequelize-cli db:migrate"
        volumes:
            - .:/usr/app
        ports:
            - "3333:3333"
        depends_on:
            - db
    db:
        image: mysql
        volumes:
            - ./data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=yes
          - MYSQL_DATABASE=sqlnode

